version: "3"

services:
  postgres:
    image: postgres:12-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 2s
      timeout: 5s
      retries: 100

  subquery-node:
    image: onfinality/subql-node-ethereum:v3.7.1
    depends_on:
      "postgres":
        condition: service_healthy
    restart: always
    environment:
      DB_USER: postgres
      DB_PASS: postgres
      DB_DATABASE: postgres
      DB_HOST: postgres
      DB_PORT: 5432
    volumes:
      - ./:/app
    command:
      # - -f=ipfs://QmWuiDNHt1JUJcZUMNRjn7kzNrPZK4zieos5yH7qMK9B5z
      - -f=ipfs://QmYoH4zGLo9Nyy5KcQXEc1ZV7U8VGQ1siYgzEkFaJ4fDWg  # v3
      # - -f=./app
      - --db-schema=euphrates
      - --workers=2
      - --batch-size=20
      - --unfinalized-blocks=false
      - --disable-historical
      - --network-endpoint=wss://eth-rpc-acala.aca-api.network
      - --log-level=info
    healthcheck:
      test: ["CMD", "curl", "-f", "http://subquery-node:3000/ready"]
      interval: 3s
      timeout: 5s
      retries: 10
